export const propertyConfig = {
    initialProps: {
        border: 0.07,
        borderColor: "#212121",
        rounded: 0,
        display: "none",
        flexDirection: "row",
        gap: 0,
        bgColor: "#bfdbfe",
        gridCols: "1",
        gridRows: "1",
        gridGap: 0,
        items: "start",
        justify: "start",
        grow: false,
        textSize: 1,
        textColor: "#212121",
        fontWeight: 400,
        leading: 1.5,
        padding: 0,
        margin: 0,
        minWidth: 8,
        minHeight: 8,
        textAlign: "left",
        overflow: "visible",
        whitespace: "normal",
        scroll: false,
    },
    sections: [
        {
            title: "Size",
            properties: [
                { key: "minWidth", label: "Min Width", type: "slider", min: 0.5, max: 32, step: 0.01 },
                { key: "minHeight", label: "Min Height", type: "slider", min: 0.5, max: 32, step: 0.01 },
            ],
        },
        {
            title: "Border",
            properties: [
                { key: "border", label: "Border Width", type: "slider", min: 0, max: 1, step: 0.01 },
                { key: "borderColor", label: "Border Color", type: "color" },
                { key: "rounded", label: "Roundedness", type: "slider", min: 0, max: 3, step: 0.01 },
            ],
        },
        {
            title: "Text",
            properties: [
                { key: "textSize", label: "Text Size", type: "slider", min: 0.5, max: 10, step: 0.01 },
                { key: "textColor", label: "Text Color", type: "color" },
                { key: "fontWeight", label: "Font Weight", type: "slider", min: 100, max: 900, step: 100 },
                { key: "leading", label: "Line Height", type: "slider", min: 0, max: 3, step: 0.1 },
                { key: "textAlign", label: "Text Align", type: "select", options: ["left", "center", "right"] },
            ],
        },
        {
            title: "Spacing",
            properties: [
                { key: "padding", label: "Padding", type: "slider", min: -1, max: 4, step: 0.01 },
                { key: "margin", label: "Margin", type: "slider", min: -1, max: 4, step: 0.01 },
                { key: "gap", label: "Gap", type: "slider", min: 0, max: 4, step: 0.01 },
            ],
        },
        {
            title: "Layout",
            properties: [
                { key: "display", label: "Display", type: "select", options: ["none", "flex", "grid"] },
                { key: "flexDirection", label: "Direction", type: "select", options: ["row", "col"], 
                  showIf: (props) => props.display === "flex" },
                { key: "items", label: "Items", type: "select", 
                  options: ["start", "center", "end", "stretch"],
                  showIf: (props) => props.display === "flex" },
                { key: "justify", label: "Justify", type: "select",
                  options: ["start", "center", "end", "between", "around", "evenly"],
                  showIf: (props) => props.display === "flex" },
                { key: "grow", label: "Grow", type: "toggle",
                  showIf: (props) => props.display === "flex" },
                { key: "gridCols", label: "Grid Columns", type: "select",
                  options: ["1", "2", "3", "4", "5", "6"],
                  showIf: (props) => props.display === "grid" },
                { key: "gridRows", label: "Grid Rows", type: "select",
                  options: ["1", "2", "3", "4", "5", "6"],
                  showIf: (props) => props.display === "grid" },
                { key: "gridGap", label: "Grid Gap", type: "slider",
                  min: 0, max: 4, step: 0.1,
                  showIf: (props) => props.display === "grid" },
            ],
        },
        {
            title: "Colors",
            properties: [
                { key: "bgColor", label: "Background Color", type: "color" },
            ],
        },
        {
            title: "Other",
            properties: [
                { key: "overflow", label: "Overflow", type: "select",
                  options: ["visible", "hidden", "scroll", "auto"] },
                { key: "whitespace", label: "Whitespace", type: "select",
                  options: ["normal", "nowrap", "pre", "pre-line", "pre-wrap"] },
                { key: "scroll", label: "Scroll", type: "toggle" },
            ],
        },
    ],
};
